Added hyakvnc_check_updates() to check for updates on a specified interval and prompt to pull if there are updates

diff --git a/hyakvnc b/hyakvnc
--- a/hyakvnc
+++ b/hyakvnc
@@ -5,14 +5,14 @@
 if [[ "${BASH_VERSINFO:-0}" -lt 4 ]]; then
 	echo "Requires Bash version > 4.x"
 	exit 1
-fi  
+fi
 
 # Check Bash version 4.4 or greater:
 case "${BASH_VERSION:-0}" in
-4*) if [[ "${BASH_VERSINFO[1]:-0}" -lt 4 ]]; then 
+4*) if [[ "${BASH_VERSINFO[1]:-0}" -lt 4 ]]; then
 	echo "Requires Bash version > 4.x"
 	exit 1
-	fi ;;
+fi ;;
 
 *) ;;
 esac
@@ -20,8 +20,8 @@ esac
 # Only enable these shell behaviours if we're not being sourced
 if ! (return 0 2>/dev/null); then
 	[[ -n "${XDEBUG:-}" ]] && set -x # %% Set XDEBUG to print commands as they are executed
-	set -o pipefail                # Use last non-zero exit code in a pipeline
-	set -o errtrace                # Ensure the error trap handler is inherited
+	set -o pipefail                  # Use last non-zero exit code in a pipeline
+	set -o errtrace                  # Ensure the error trap handler is inherited
 	# set -o errexit                 # Exit on error
 	# shopt -qs inherit_errexit      # Ensure subshells exit on error
 fi
@@ -30,13 +30,15 @@ fi
 HYAKVNC_VERSION="0.3.1"
 
 # ## App preferences:
-HYAKVNC_DIR="${HYAKVNC_DIR:-${HOME}/.hyakvnc}"          # %% Local directory to store application data (default: `$HOME/.hyakvnc`)
-HYAKVNC_CONFIG_FILE="${HYAKVNC_DIR}/hyakvnc-config.env" # %% Configuration file to use (default: `$HYAKVNC_DIR/hyakvnc-config.env`)
-HYAKVNC_LOG_FILE="${HYAKVNC_LOG_FILE:-${HYAKVNC_DIR}/hyakvnc.log}" # %% Log file to use (default: `$HYAKVNC_DIR/hyakvnc.log`)
-HYAKVNC_LOG_LEVEL="${HYAKVNC_LOG_LEVEL:-INFO}"                     # %% Log level to use for interactive output (default: `INFO`)
-HYAKVNC_LOG_FILE_LEVEL="${HYAKVNC_LOG_FILE_LEVEL:-DEBUG}"          # %% Log level to use for log file output (default: `DEBUG`)
-HYAKVNC_SSH_HOST="${HYAKVNC_SSH_HOST:-klone.hyak.uw.edu}"          # %% Default SSH host to use for connection strings (default: `klone.hyak.uw.edu`)
-HYAKVNC_DEFAULT_TIMEOUT="${HYAKVNC_DEFAULT_TIMEOUT:-30}"           # %% Seconds to wait for most commands to complete before timing out (default: `30`)
+HYAKVNC_DIR="${HYAKVNC_DIR:-${HOME}/.hyakvnc}"                        # %% Local directory to store application data (default: `$HOME/.hyakvnc`)
+HYAKVNC_REPO_DIR="${HYAKVNC_REPO_DIR:-${HYAKVNC_DIR}/hyakvnc}"        # Local directory to store git repository (default: `$HYAKVNC_DIR/hyakvnc`)
+HYAKVNC_CHECK_UPDATE_FREQUENCY="${HYAKVNC_CHECK_UPDATE_FREQUENCY:-0}" # %% How often to check for updates in `[d]`ays or `[m]`inutes (default: `0` for every time. Use `1d` for daily, `10m` for every 10 minutes, etc. `-1` to disable.)
+HYAKVNC_CONFIG_FILE="${HYAKVNC_DIR}/hyakvnc-config.env"               # %% Configuration file to use (default: `$HYAKVNC_DIR/hyakvnc-config.env`)
+HYAKVNC_LOG_FILE="${HYAKVNC_LOG_FILE:-${HYAKVNC_DIR}/hyakvnc.log}"    # %% Log file to use (default: `$HYAKVNC_DIR/hyakvnc.log`)
+HYAKVNC_LOG_LEVEL="${HYAKVNC_LOG_LEVEL:-INFO}"                        # %% Log level to use for interactive output (default: `INFO`)
+HYAKVNC_LOG_FILE_LEVEL="${HYAKVNC_LOG_FILE_LEVEL:-DEBUG}"             # %% Log level to use for log file output (default: `DEBUG`)
+HYAKVNC_SSH_HOST="${HYAKVNC_SSH_HOST:-klone.hyak.uw.edu}"             # %% Default SSH host to use for connection strings (default: `klone.hyak.uw.edu`)
+HYAKVNC_DEFAULT_TIMEOUT="${HYAKVNC_DEFAULT_TIMEOUT:-30}"              # %% Seconds to wait for most commands to complete before timing out (default: `30`)
 
 # hyakvnc_load_config()
 # Load the hyakvnc configuration from the config file
@@ -48,7 +50,7 @@ function hyakvnc_load_config {
 	# Read each line of the parsed config file and export the variable:
 	while IFS=$'\n' read -r line; do
 		# Get the variable name by removing everything after the equals sign. Uses nameref to allow indirect assignment (see https://gnu.org/software/bash/manual/html_node/Shell-Parameters.html):
-		declare -n varref="${line%%=*}" 
+		declare -n varref="${line%%=*}"
 		# Evaluate the right-hand side of the equals sign:
 		varref="$(bash --restricted --posix -c "echo ${line#*=}" || true)"
 		# Export the variable:
@@ -65,12 +67,15 @@ fi
 
 # ## VNC preferences:
 HYAKVNC_VNC_PASSWORD="${HYAKVNC_VNC_PASSWORD:-password}" # %% Password to use for new VNC sessions (default: `password`)
-HYAKVNC_VNC_DISPLAY="${HYAKVNC_VNC_DISPLAY:-:10}"         # %% VNC display to use (default: `:1`)
+HYAKVNC_VNC_DISPLAY="${HYAKVNC_VNC_DISPLAY:-:10}"        # %% VNC display to use (default: `:1`)
 
 HYAKVNC_MACOS_VNC_VIEWER_BUNDLEIDS="${HYAKVNC_MACOS_VNC_VIEWER_BUNDLEIDS:-com.turbovnc.vncviewer.VncViewer com.realvnc.vncviewer com.tigervnc.vncviewer}" # macOS bundle identifiers for VNC viewer executables (default: `com.turbovnc.vncviewer com.realvnc.vncviewer com.tigervnc.vncviewer`)
 
 # ## Apptainer preferences:
-HYAKVNC_APPTAINER_BIN="${HYAKVNC_APPTAINER_BIN:-apptainer}"    # %% Name of apptainer binary (default: `apptainer`)
+HYAKVNC_APPTAINER_BIN="${HYAKVNC_APPTAINER_BIN:-apptainer}" # %% Name of apptainer binary (default: `apptainer`)
+
+HYAKVNC_LOGIN_NODE_APPTAINER_BIN="${HYAKVNC_LOGIN_NODE_APPTAINER_BIN:-/sw/apptainer/default/bin/apptainer}" # Path to apptainer binary on login node(default: `/sw/apptainer/default/bin/apptainer`)
+
 HYAKVNC_APPTAINER_CONTAINER="${HYAKVNC_APPTAINER_CONTAINER:-}" # %% Path to container image to use (default: (none; set by `--container` option))
 
 HYAKVNC_APPTAINER_APP_VNCSERVER="${HYAKVNC_APPTAINER_APP_VNCSERVER:-vncserver}" # %% Name of app in the container that starts the VNC session (default: `vncserver`)
@@ -174,6 +179,121 @@ function log {
 
 	if [[ "${curlogfilelevelno}" -ge "${levelno}" ]]; then
 		echo "${level}:${logfilefuncname}${*:-}" >>"${HYAKVNC_LOG_FILE:-/dev/null}"
+	fi
+}
+
+# ## Update functions:
+
+# hyakvnc_check_updates()
+# Check if a hyakvnc update is available
+# Arguments: None
+
+function hyakvnc_check_updates {
+	if [[ "${HYAKVNC_CHECK_UPDATE_FREQUENCY:-0}" == "-1" ]]; then
+		log DEBUG "Skipping update check"
+		return 0
+	fi
+
+	if [[ "${HYAKVNC_CHECK_UPDATE_FREQUENCY:-0}" != "0" ]]; then
+		local update_frequency_unit="${HYAKVNC_CHECK_UPDATE_FREQUENCY:0-1}"
+		local update_frequency_value="${HYAKVNC_CHECK_UPDATE_FREQUENCY:0:-1}"
+		local find_m_arg=()
+
+		case "${update_frequency_unit:=d}" in
+		d)
+			find_m_arg+=(-mtime "+${update_frequency_value:=0}")
+			;;
+		m)
+			find_m_arg+=(-mmin "+${update_frequency_value:=0}")
+			;;
+		*)
+			log ERROR "Invalid update frequency unit: ${update_frequency_unit}. Please use [d]ays or [m]inutes."
+			exit 1
+			;;
+		esac
+
+		log DEBUG "Checking if ${HYAKVNC_REPO_DIR}/.last_update_check is older than ${update_frequency_value}${update_frequency_unit}..."
+
+		if [[ -r "${HYAKVNC_REPO_DIR}/.last_update_check" ]] && [[ -z $(find "${HYAKVNC_REPO_DIR}/.last_update_check" -type f "${find_m_arg[@]}" -print || true) ]]; then
+			log DEBUG "Skipping update check because the last check was less than ${update_frequency_value}${update_frequency_unit} ago."
+			return 0
+		fi
+
+		log DEBUG "Checking for updates because the last check was more than ${update_frequency_value}${update_frequency_unit} ago."
+	fi
+
+	log DEBUG "Checking for updates... "
+	# Check if git is installed:
+	command -v git >/dev/null 2>&1 || {
+		log WARN "git is not installed. Can't check for updates"
+		return 0
+	}
+
+	# Check if git is available and that the git directory is a valid git repository:
+	git -C "${HYAKVNC_REPO_DIR}" tag >/dev/null 2>&1 || {
+		log DEBUG "Configured git directory ${HYAKVNC_REPO_DIR} doesn't seem to be a valid git repository. Can't check for updates"
+		return 0
+	}
+
+	local cur_branch
+	cur_branch="$(git -C "${HYAKVNC_REPO_DIR}" branch --show-current 2>&1 || true)"
+	if [[ "${cur_branch:-}" != "main" ]]; then
+		log WARN "Current branch is ${cur_branch}. Please switch to the main branch to get updates. Skipping update check!"
+		return 0
+	fi
+
+	local cur_date
+	cur_date="$(git -C "${HYAKVNC_REPO_DIR}" show -s --format=%cd --date=human-local main || echo ???)"
+	log INFO "The installed version was published ${cur_date}"
+
+	touch "${HYAKVNC_REPO_DIR}/.last_update_check"
+
+	# Get hash of local HEAD:
+	if [[ "$(git -C "${HYAKVNC_REPO_DIR}" rev-parse main || true)" == "$(git -C "${HYAKVNC_REPO_DIR}" ls-remote --heads --refs origin main | cut -f1 || true)" ]]; then
+		log INFO "hyakvnc is up to date."
+		return 0
+	fi
+
+	git -C "${HYAKVNC_REPO_DIR}" fetch --quiet origin main || {
+		log DEBUG "Failed to fetch from remote"
+		return 0
+	}
+
+	local nchanges
+	nchanges="$(git -C "${HYAKVNC_REPO_DIR}" rev-list HEAD...origin/main --count || echo 0)"
+	if [[ "${nchanges}" -gt 0 ]]; then
+		local new_date
+		new_date="$(git -C "${HYAKVNC_REPO_DIR}" show -s --format=%cd --date=human-local origin/main || echo ???)"
+		log INFO "Found ${nchanges} updates. Most recent: ${new_date}"
+
+		[[ -t 0 ]] || {
+			log INFO "Not updating hyakvnc because it is not running interactively."
+			return 0
+		}
+
+		while true; do # Ask user if they want to update
+			local choice
+			read -r -p "Would you like to update hyakvnc? [y/n] " choice
+			case "${choice}" in
+			y | Y | yes | Yes)
+				log INFO "Updating hyakvnc..."
+				git -C "${HYAKVNC_REPO_DIR}" pull --quiet origin main || {
+					log DEBUG "Failed to pull from remote"
+					return 0
+				}
+				log INFO "Successfully updated hyakvnc. Restarting..."
+				echo
+				exec "${0}" "${@}" # Restart hyakvnc
+				;;
+			n | N | no | No)
+				log INFO "Not updating hyakvnc"
+				return 0
+				;;
+			*)
+				echo "Please enter y or n"
+				;;
+			esac
+		done
 	fi
 }
 
@@ -447,7 +567,10 @@ function print_connection_info {
 	[[ -n "${node}" ]] || node=$(squeue -h -j "${jobid}" -o '%N' | grep -o -m 1 -E '\S+') || log DEBUG "Failed to get node for job ${jobid} from squeue"
 	if [[ -r "${HYAKVNC_DIR}/jobs/${jobid}/vnc/hostname" ]] && launch_hostname=$(cat "${HYAKVNC_DIR}/jobs/${jobid}/vnc/hostname" 2>/dev/null || true) && [[ -n "${launch_hostname:-}" ]]; then
 		[[ "${node}" = "${launch_hostname}" ]] || log WARN "Node for ${jobid} from hostname file (${HYAKVNC_DIR}/jobs/${jobid}/vnc/hostname) (${launch_hostname:-}) does not match node from squeue (${node}). Was the job restarted?"
-		[[ -z "${node}" ]] && { log DEBUG "Node for ${jobid} from squeue is blank. Setting to ${launch_hostname}"; node="${launch_hostname}"; }
+		[[ -z "${node}" ]] && {
+			log DEBUG "Node for ${jobid} from squeue is blank. Setting to ${launch_hostname}"
+			node="${launch_hostname}"
+		}
 	else
 		log WARN "Failed to get originally launched node for job ${jobid} from ${HYAKVNC_DIR}/jobs/${jobid}/hostname"
 	fi
@@ -651,7 +774,8 @@ function cmd_create {
 			break
 			;;
 		-*)
-			log ERROR "Unknown option: ${1:-}\n"; exit 1
+			log ERROR "Unknown option: ${1:-}\n"
+			exit 1
 			;;
 		*)
 			break
@@ -738,12 +862,18 @@ function cmd_create {
 						;;
 
 					n | N) log WARN "Not adding APPTAINER_CACHEDIR to your shell's startup file. You may need to do this again in the future." ;;
-					*) log ERROR "Invalid choice ${choice2:-}."; exit 1;;
+					*)
+						log ERROR "Invalid choice ${choice2:-}."
+						exit 1
+						;;
 					esac
 					;;
 
 				n | N) log WARN "Not setting APPTAINER_CACHEDIR. You may encounter problems with storage space." ;;
-				*) log ERROR "Invalid choice ${choice1:-}."; exit 1;;
+				*)
+					log ERROR "Invalid choice ${choice1:-}."
+					exit 1
+					;;
 				esac
 			fi
 		fi
@@ -769,8 +899,14 @@ function cmd_create {
 	# Set up the jobs directory:
 	local alljobsdir jobdir
 	alljobsdir="${HYAKVNC_DIR}/jobs"
-	mkdir -p "${alljobsdir}" || { log ERROR "Failed to create directory ${alljobsdir}"; exit 1; }
-	mkdir -p "${HYAKVNC_SLURM_OUTPUT_DIR}" || { log ERROR "Failed to create directory ${HYAKVNC_SLURM_OUTPUT_DIR}"; exit 1; }
+	mkdir -p "${alljobsdir}" || {
+		log ERROR "Failed to create directory ${alljobsdir}"
+		exit 1
+	}
+	mkdir -p "${HYAKVNC_SLURM_OUTPUT_DIR}" || {
+		log ERROR "Failed to create directory ${HYAKVNC_SLURM_OUTPUT_DIR}"
+		exit 1
+	}
 
 	apptainer_start_args+=("run" "--app" "${HYAKVNC_APPTAINER_APP_VNCSERVER}")
 	apptainer_start_args+=("--writable-tmpfs")
@@ -805,7 +941,10 @@ function cmd_create {
 
 	log INFO "Launching job with command: sbatch ${sbatch_args[*]}"
 
-	sbatch_result=$(sbatch "${sbatch_args[@]}") || { log ERROR "Failed to launch job"; exit 1; }
+	sbatch_result=$(sbatch "${sbatch_args[@]}") || {
+		log ERROR "Failed to launch job"
+		exit 1
+	}
 
 	# Quit if no job ID was returned:
 	[[ -z "${sbatch_result:-}" ]] && {
@@ -845,7 +984,10 @@ function cmd_create {
 			log DEBUG "Job ${launched_jobid} is ${squeue_result}"
 			break
 			;;
-		*) log ERROR "Job ${launched_jobid} is in unexpected state ${squeue_result}"; exit 1 ;;
+		*)
+			log ERROR "Job ${launched_jobid} is in unexpected state ${squeue_result}"
+			exit 1
+			;;
 		esac
 	done
 
@@ -853,11 +995,14 @@ function cmd_create {
 	start=${EPOCHSECONDS:-}
 	while true; do
 		if ((EPOCHSECONDS - start > HYAKVNC_DEFAULT_TIMEOUT)); then
-			log ERROR "Timed out waiting for job to create its directory at ${jobdir}";
+			log ERROR "Timed out waiting for job to create its directory at ${jobdir}"
 			exit 1
 		fi
 		sleep 1
-		[[ ! -d "${jobdir}" ]] && { log TRACE "Job directory does not exist yet"; continue; }
+		[[ ! -d "${jobdir}" ]] && {
+			log TRACE "Job directory does not exist yet"
+			continue
+		}
 		break
 	done
 
@@ -891,7 +1036,8 @@ function cmd_create {
 	start=${EPOCHSECONDS:-}
 	while true; do
 		if ((EPOCHSECONDS - start > HYAKVNC_DEFAULT_TIMEOUT)); then
-			log ERROR "Timed out waiting for job to open its directories"; exit 1
+			log ERROR "Timed out waiting for job to open its directories"
+			exit 1
 		fi
 		sleep 1
 		[[ ! -d "${jobdir}" ]] && log TRACE "Job directory does not exist yet" && continue
@@ -955,7 +1101,8 @@ function cmd_status {
 			shift
 			;;
 		-*)
-			log ERROR "Unknown option: ${1:-}\n"; exit 1
+			log ERROR "Unknown option: ${1:-}\n"
+			exit 1
 			;;
 		*)
 			break
