Updated instructions

diff --git a/hyakvnc b/hyakvnc
--- a/hyakvnc
+++ b/hyakvnc
@@ -16,26 +16,26 @@ set -o errtrace # Ensure the error trap handler is inherited
 HYAKVNC_VERSION="0.3.0"
 
 # ## App preferences:
-HYAKVNC_DIR="${HYAKVNC_DIR:-${HOME}/.hyakvnc}"                     # %% Local directory to store application data (default: `$HOME/.hyakvnc`)
-HYAKVNC_CONFIG_FILE="${HYAKVNC_DIR}/hyakvnc-config.env"            # %% Configuration file to use (default: `$HYAKVNC_DIR/hyakvnc-config.env`)
+HYAKVNC_DIR="${HYAKVNC_DIR:-${HOME}/.hyakvnc}"          # %% Local directory to store application data (default: `$HOME/.hyakvnc`)
+HYAKVNC_CONFIG_FILE="${HYAKVNC_DIR}/hyakvnc-config.env" # %% Configuration file to use (default: `$HYAKVNC_DIR/hyakvnc-config.env`)
 
 # hyakvnc_load_config()
 # Load the hyakvnc configuration from the config file
 # Arguments: None
 function hyakvnc_load_config {
-		while IFS=$'\n' read -r line; do
-			declare -n varref="${line%%=*}"
-			if [ -z "${varref:-}" ]; then
-				varref=$(bash --restricted -c "echo ${line#*=}")
-				export "${!varref}"
-			fi
-		done < <(sed -E 's/^\s*//; /^[^=]+=.*/!d' "$HYAKVNC_CONFIG_FILE")
+	[ -r "${HYAKVNC_CONFIG_FILE:-}" ] || return 0
+	while IFS=$'\n' read -r line; do
+		declare -n varref="${line%%=*}"
+		if [ -z "${varref:-}" ]; then
+			varref=$(bash --restricted -c "echo ${line#*=}")
+			export "${!varref}"
+		fi
+	done < <(sed -E 's/^\s*//; /^[^=]+=.*/!d' "$HYAKVNC_CONFIG_FILE")
 }
 # Load config if not sourced:
 if ! (return 0 2>/dev/null); then
 	hyakvnc_load_config
 fi
-
 
 HYAKVNC_LOG_FILE="${HYAKVNC_LOG_FILE:-${HYAKVNC_DIR}/hyakvnc.log}" # %% Log file to use (default: `$HYAKVNC_DIR/hyakvnc.log`)
 HYAKVNC_LOG_LEVEL="${HYAKVNC_LOG_LEVEL:-INFO}"                     # %% Log level to use for interactive output (default: `INFO`)
@@ -47,7 +47,7 @@ HYAKVNC_DEFAULT_TIMEOUT="${HYAKVNC_DEFAULT_TIMEOUT:-30}"           # %% Seconds 
 HYAKVNC_VNC_PASSWORD="${HYAKVNC_VNC_PASSWORD:-password}" # %% Password to use for new VNC sessions (default: `password`)
 HYAKVNC_VNC_DISPLAY="${HYAKVNC_VNC_DISPLAY:-:1}"         # %% VNC display to use (default: `:1`)
 
-HYAKVNC_MACOS_VNC_VIEWER_BUNDLEIDS="${HYAKVNC_MACOS_VNC_VIEWER_BUNDLEIDS:-com.turbovnc.vncviewer com.realvnc.vncviewer com.tigervnc.vncviewer}" # %% macOS bundle identifiers for VNC viewer executables (default: `com.turbovnc.vncviewer com.realvnc.vncviewer com.tigervnc.vncviewer`)
+HYAKVNC_MACOS_VNC_VIEWER_BUNDLEIDS="${HYAKVNC_MACOS_VNC_VIEWER_BUNDLEIDS:-com.turbovnc.vncviewer com.realvnc.vncviewer com.tigervnc.vncviewer}" # macOS bundle identifiers for VNC viewer executables (default: `com.turbovnc.vncviewer com.realvnc.vncviewer com.tigervnc.vncviewer`)
 
 # ## Apptainer preferences:
 HYAKVNC_APPTAINER_BIN="${HYAKVNC_APPTAINER_BIN:-apptainer}"    # %% Name of apptainer binary (default: `apptainer`)
@@ -140,13 +140,11 @@ function log {
 	fi
 }
 
-
-
 # hyakvnc_config_init()
 # Initialize the hyakvnc configuration
 # Arguments: None
 function hyakvnc_config_init {
-		
+
 	if ! check_slurm_installed; then
 		log ERROR "SLURM is not installed! Can't initialize configuration."
 		return 1
@@ -185,7 +183,7 @@ function hyakvnc_config_init {
 		[ -z "${HYAKVNC_SLURM_PARTITION}" ] && log ERROR "Failed to get default SLURM partition" && return 1
 	fi
 	export SBATCH_PARTITION="${HYAKVNC_SLURM_PARTITION}" && log TRACE "Set SBATCH_PARTITION to ${SBATCH_PARTITION}"
-	
+
 	# shellcheck disable=SC2046
 	export $(compgen -v HYAKVNC_) # Export all HYAKVNC_ variables
 }
@@ -299,7 +297,6 @@ function print_connection_info {
 	local jobid jobdir node socket_path viewer_port launch_hostname ssh_host
 	viewer_port="${HYAKVNC_LOCALHOST_PORT:-5901}"
 	ssh_host="${HYAKVNC_SSH_HOST:-klone.hyak.uw.edu}"
-
 	# Parse arguments:
 	while true; do
 		case ${1:-} in
@@ -368,11 +365,18 @@ function print_connection_info {
 ==========
 Copy and paste these instructions into a command line terminal on your local machine to connect to the VNC session.
 You may need to install a VNC client if you don't already have one.
-If you are using Windows or are having trouble, try using the manual connection information.
+
+**********
+NOTE: If you receive an error that looks like "Permission denied (publickey,gssapi-keyex,gssapi-with-mic)", you don't have an SSH key set up. To set this up quickly on Linux, macOS, or Windows (WSL2/Cygwin), open a new terminal window on your machine and enter the following 2 commands before you try again:
+
+[ ! -r ~/.ssh/id_rsa ] && ssh-keygen -t rsa -b 4096 -N '' -C "$USER@uw.edu" -f ~/.ssh/id_rsa
+ssh-copy-id -o StrictHostKeyChecking=no $USER@klone.hyak.uw.edu
+
+Se https://hyak.uw.edu/docs/setup/intracluster-keys for more information.
+**********
 ---------
 EOF
 	# Print connection instructions for each operating system:
-
 	echo "LINUX TERMINAL (bash/zsh):"
 	echo "ssh -f ${ssh_args[*]} sleep 10 && vncviewer localhost:${viewer_port}"
 	echo
@@ -388,8 +392,9 @@ EOF
 	echo
 
 	echo "WINDOWS"
-	echo "(See below)"
-	echo
+	echo "-- TurboVNC via WSL2 (recommended) or Cygwin:"
+	echo "ssh -f ${ssh_args[*]} sleep 20 && cmd.exe /c cmd /c \"\$(cmd.exe /c where \"C:\Program Files\TurboVNC;C:\Program Files(x86)\TurboVNC:vncviewerw.bat\")\" localhost:${viewer_port}"
+
 
 	echo "MANUAL CONNECTION INFORMATION"
 	echo "Configure your SSH client to connect to the address ${node} with username ${USER} through the \"jump host\" (possibly labeled a via, proxy, or gateway host) at the address \"${HYAKVNC_SSH_HOST}\"."
@@ -885,21 +890,27 @@ Show connection information for a HyakVNC sesssion
 Usage: hyakvnc show <jobid>
 	
 Description:
-	Show connection information for a HyakVNC sesssion.
+	Show connection information for a HyakVNC sesssion. 
 	If no job ID is provided, a menu will be shown to select from running jobs.
-
+	
 Options:
 	-h, --help	Show this help message and exit
+	-s, --os	Show connection information for the specified operating system (default: ${HYAKVNC_DEFAULT_OS})
 
 Examples:
 	# Show connection information for session running on job 123456:
 	hyakvnc show 123456
+	# Interactively select a job to show connection information for:
+	hyakvnc show
+
+	# Show connection information for session running on job 123456 for macOS:
+	hyakvnc show -s mac 123456
 EOF
 }
 
 # cmd_show()
 function cmd_show {
-	local jobid
+	local jobid running_jobids
 	# Parse arguments:
 	while true; do
 		case "${1:-}" in
@@ -922,7 +933,7 @@ function cmd_show {
 		esac
 	done
 
-	if [ -z "${jobid}" ]; then
+	if [ -z "${jobid:-}" ]; then
 		if [ -t 0 ]; then
 			echo "Reading available job IDs to select from a menu"
 			running_jobids=$(squeue --noheader --format '%j %i' | grep -E "^${HYAKVNC_SLURM_JOB_PREFIX}" | grep -oE '[0-9]+$') || { log WARN "Found no running jobs with names that match the prefix ${HYAKVNC_SLURM_JOB_PREFIX}" && return 1; }
@@ -934,11 +945,10 @@ function cmd_show {
 	fi
 	[ -z "${jobid}" ] && {
 		log ERROR "Must specify running job IDs"
-		exit 1
+		return 1
 	}
 	running_jobids=$(squeue --job "${jobid}" --noheader --format '%j %i' | grep -E "^${HYAKVNC_SLURM_JOB_PREFIX}" | grep -oE '[0-9]+$') || { log WARN "Found no running job for job ${jobid} with names that match the prefix ${HYAKVNC_SLURM_JOB_PREFIX}" && return 1; }
-
-	print_connection_info -j "$jobid" || { log ERROR "Failed to print connection info for job ${jobid}" && return 1; }
+	print_connection_info -j "${jobid}" || { log ERROR "Failed to print connection info for job ${jobid}" && return 1; }
 	return 0
 }
 
@@ -1177,7 +1187,6 @@ function main {
 			;;
 		esac
 	done
-
 
 	if [ "$action" != "cmd_help" ] && [ "$action" != "cmd_install" ]; then
 		if [ "$action" != "cmd_config" ]; then
