Formatting

diff --git a/hyakvnc b/hyakvnc
--- a/hyakvnc
+++ b/hyakvnc
@@ -1,21 +1,20 @@
 #! /usr/bin/env bash
-HYAKVNC_VERSION="0.3.0"
+# hyakvnc - A script to launch VNC sessions on Hyak
 
-# Initialize
-[ -n "${XDEBUG:-}" ] && set -x # %% Set XDEBUG to print commands as they are executed
+# Check Bash version:
 [ "${BASH_VERSINFO:-0}" -lt 4 ] && echo "Requires Bash version > 4.x" && exit 1
 
 # Only enable these shell behaviours if we're not being sourced
 if ! (return 0 2>/dev/null); then
-	# set -o errexit  # Exit on most errors
-	set -o pipefail # Use last non-zero exit code in a pipeline
+	set -o pipefail                # Use last non-zero exit code in a pipeline
+	[ -n "${XDEBUG:-}" ] && set -x # %% Set XDEBUG to print commands as they are executed
 fi
 
 set -o errtrace # Ensure the error trap handler is inherited
 
-# hyakvnc - A script to launch VNC sessions on Hyak
-
 # # Preferences and settings:
+HYAKVNC_VERSION="0.3.0"
+
 # ## App preferences:
 HYAKVNC_DIR="${HYAKVNC_DIR:-${HOME}/.hyakvnc}"                     # %% Local directory to store application data
 HYAKVNC_LOG_FILE="${HYAKVNC_LOG_FILE:-${HYAKVNC_DIR}/hyakvnc.log}" # $$ Log file to use
@@ -43,7 +42,7 @@ HYAKVNC_APPTAINER_ADD_BINDPATHS="${HYAKVNC_APPTAINER_ADD_BINDPATHS:-}"          
 HYAKVNC_APPTAINER_ADD_ENVVARS="${HYAKVNC_APPTAINER_ADD_ENVVARS:-}"                                     #  %% Environment variables to add to before invoking apptainer
 HYAKVNC_APPTAINER_ADD_ARGS="${HYAKVNC_APPTAINER_ADD_ARGS:-}"                                           #  %% Additional arguments to give apptainer
 
-# == Slurm preferences:
+# ## Slurm preferences:
 HYAKVNC_SLURM_JOB_PREFIX="${HYAKVNC_SLURM_JOB_PREFIX:-hyakvnc-}"    # %% Prefix to use for hyakvnc SLURM job names
 HYAKVNC_SLURM_SUBMIT_TIMEOUT="${HYAKVNC_SLURM_SUBMIT_TIMEOUT:-120}" # %% How long after submitting via sbatch to wait for the job to start before timing out
 
@@ -59,16 +58,16 @@ HYAKVNC_SLURM_MEM="${HYAKVNC_SLURM_MEM:-${SBATCH_MEM:-4G}}"                     
 HYAKVNC_SLURM_CPUS="${HYAKVNC_SLURM_CPUS:-4}"                                       # %% Number of CPUs to request (passed by --cpus-per-task to sbatch)
 HYAKVNC_SLURM_TIMELIMIT="${HYAKVNC_SLURM_TIMELIMIT:-${SBATCH_TIMELIMIT:-12:00:00}}" # %% Time limit for SLURM job
 
-# = Global variables (using CamelCase):
+# # Global variables (using CamelCase):
 declare -a Launched_JobIDs # Declare array of launched jobs
 Launched_JobIDs=()         # Array of launched jobs
 
-# == Log levels for log() function:
+# ## Log levels for log() function:
 declare -A Log_Levels Log_Level_Colors # Declare Log_Levels and Log_Level_Colors arrays
 Log_Levels=(["OFF"]=0 ["FATAL"]=1 ["ERROR"]=2 ["WARN"]=3 ["INFO"]=4 ["DEBUG"]=5 ["TRACE"]=6 ["ALL"]=100)
 Log_Level_Colors=(["FATAL"]=5 ["ERROR"]=1 ["WARN"]=3 ["INFO"]=4 ["DEBUG"]=6 ["TRACE"]=2)
 
-# = Utility functions
+# # Utility functions
 
 # log()
 # Log a message to the stderr and the log file if the log level is high enough
@@ -164,7 +163,7 @@ function get_slurm_job_info {
 	squeue "${squeue_args[@]}"
 }
 
-# get_squeue_job_status
+# get_squeue_job_status()
 # Get the status of a SLURM job, given a job ID
 function get_squeue_job_status {
 	local jobid="${1:-}"
@@ -172,7 +171,7 @@ function get_squeue_job_status {
 	squeue -j "${1}" -h -o '%T' || { log ERROR "Failed to get status for job ${jobid}" && return 1; }
 }
 
-# stop_hyakvnc_session
+# stop_hyakvnc_session()
 # Stop a Hyak VNC session, given a job ID
 function stop_hyakvnc_session {
 	local jobid should_cancel no_rm
@@ -349,36 +348,40 @@ function cleanup_launched_jobs_and_exit {
 	exit 1
 }
 
-# = Commands
+# # Commands
+
+# ## Command: create
+
+# help_create()
 function help_create {
 	cat <<EOF
 Usage: hyakvnc create [create options...] -c <container> [extra args to pass to apptainer...]
 
 Description:
-  Create a VNC session on Hyak.
+	Create a VNC session on Hyak.
 
 Options:
-  -h, --help	Show this help message and exit
-  -c, --container	Path to container image (required)
-  -A, --account	Slurm account to use (default: ${HYAKVNC_SLURM_ACCOUNT})
-  -p, --partition	Slurm partition to use (default: ${HYAKVNC_SLURM_PARTITION})
-  -C, --cpus	Number of CPUs to request (default: ${HYAKVNC_SLURM_CPUS})
-  -m, --mem	Amount of memory to request (default: ${HYAKVNC_SLURM_MEM})
-  -t, --timelimit	Slurm timelimit to use (default: ${HYAKVNC_SLURM_TIMELIMIT})
-  -g, --gpus	Number of GPUs to request (default: ${HYAKVNC_SLURM_GPUS})
+	-h, --help	Show this help message and exit
+	-c, --container	Path to container image (required)
+	-A, --account	Slurm account to use (default: ${HYAKVNC_SLURM_ACCOUNT})
+	-p, --partition	Slurm partition to use (default: ${HYAKVNC_SLURM_PARTITION})
+	-C, --cpus	Number of CPUs to request (default: ${HYAKVNC_SLURM_CPUS})
+	-m, --mem	Amount of memory to request (default: ${HYAKVNC_SLURM_MEM})
+	-t, --timelimit	Slurm timelimit to use (default: ${HYAKVNC_SLURM_TIMELIMIT})
+	-g, --gpus	Number of GPUs to request (default: ${HYAKVNC_SLURM_GPUS})
 
 Extra arguments:
-  Any extra arguments will be passed to apptainer run.
-  See 'apptainer run --help' for more information.
+	Any extra arguments will be passed to apptainer run.
+	See 'apptainer run --help' for more information.
 
 Examples:
-  # Create a VNC session using the container ~/containers/mycontainer.sif
-  # Use the SLURM account escience, the partition gpu-a40, 4 CPUs, 1GB of memory, 1 GPU, and 1 hour of time
-  hyakvnc create -c ~/containers/mycontainer.sif -A escience -p gpu-a40 -C 4 -m 1G -t 1:00:00 -g 1
+	# Create a VNC session using the container ~/containers/mycontainer.sif
+	# Use the SLURM account escience, the partition gpu-a40, 4 CPUs, 1GB of memory, 1 GPU, and 1 hour of time
+	hyakvnc create -c ~/containers/mycontainer.sif -A escience -p gpu-a40 -C 4 -m 1G -t 1:00:00 -g 1
 EOF
 }
 
-# create
+# cmd_create()
 function cmd_create {
 	local apptainer_start_args=()
 	local sbatch_args=(--parsable)
@@ -577,28 +580,30 @@ function cmd_create {
 	return 0
 }
 
-# == COMMAND: status
-# help for status command:
+# ## COMMAND: status
+
+# help_status()
 function help_status {
 	cat <<EOF
 Usage: hyakvnc status [status options...]
 
 Description:
-  Check status of VNC session(s) on Hyak.
+	Check status of VNC session(s) on Hyak.
 
 Options:
-  -h, --help	Show this help message and exit
-  -d, --debug	Print debug info
-  -j, --jobid	Only check status of provided SLURM job ID (optional)
+	-h, --help	Show this help message and exit
+	-d, --debug	Print debug info
+	-j, --jobid	Only check status of provided SLURM job ID (optional)
 
 Examples:
-  # Check the status of job no. 12345:
-  hyakvnc status -j 12345
-  # Check the status of all VNC jobs:
-  hyakvnc status
+	# Check the status of job no. 12345:
+	hyakvnc status -j 12345
+	# Check the status of all VNC jobs:
+	hyakvnc status
 EOF
 }
-# status command:
+
+# cmd_status()
 function cmd_status {
 	local running_jobid running_jobids
 	while true; do
@@ -642,31 +647,35 @@ function cmd_status {
 	done
 }
 
+# ## COMMAND: stop
+
+# help_stop()
 function help_stop {
 	cat <<EOF
 Usage: hyakvnc stop [-a] [<jobids>...]
 	
 Description:
-  Stop a provided HyakVNC sesssion and clean up its job directory.
-  If no job ID is provided, a menu will be shown to select from running jobs.
+	Stop a provided HyakVNC sesssion and clean up its job directory.
+	If no job ID is provided, a menu will be shown to select from running jobs.
 
 Options:
-  -h, --help	Show this help message and exit
-  -n, --no-cancel	Don't cancel the SLURM job
-  -a, --all	Stop all jobs
+	-h, --help	Show this help message and exit
+	-n, --no-cancel	Don't cancel the SLURM job
+	-a, --all	Stop all jobs
 
 Examples:
-  # Stop a VNC session running on job 123456:
-  hyakvnc stop 123456
-  # Stop a VNC session running on job 123456 and do not cancel the job:
-  hyakvnc stop --no-cancel 123456
-  # Stop all VNC sessions:
-  hyakvnc stop -a
-  # Stop all VNC sessions but do not cancel the jobs:
-  hyakvnc stop -a -n
+	# Stop a VNC session running on job 123456:
+	hyakvnc stop 123456
+	# Stop a VNC session running on job 123456 and do not cancel the job:
+	hyakvnc stop --no-cancel 123456
+	# Stop all VNC sessions:
+	hyakvnc stop -a
+	# Stop all VNC sessions but do not cancel the jobs:
+	hyakvnc stop -a -n
 EOF
 }
 
+# cmd_stop()
 function cmd_stop {
 	local jobids all jobid nocancel stop_hyakvnc_session_args
 	should_cancel=1
@@ -728,23 +737,27 @@ function cmd_stop {
 	return 0
 }
 
+# ## COMMAND: show
+
+# help_show()
 function help_show {
 	cat <<EOF
 Usage: hyakvnc show <jobid>
- 
+	
 Description:
-  Show connection information for a HyakVNC sesssion.
-  If no job ID is provided, a menu will be shown to select from running jobs.
+	Show connection information for a HyakVNC sesssion.
+	If no job ID is provided, a menu will be shown to select from running jobs.
 
 Options:
-  -h, --help	Show this help message and exit
+	-h, --help	Show this help message and exit
 
 Examples:
-  # Show connection information for session running on job 123456:
-  hyakvnc show 123456
+	# Show connection information for session running on job 123456:
+	hyakvnc show 123456
 EOF
 }
 
+# cmd_show()
 function cmd_show {
 	local jobid
 	# Parse arguments:
@@ -786,26 +799,30 @@ function cmd_show {
 	return 0
 }
 
+# ## COMMAND: install
+
+# help_install()
 function help_install {
 	cat <<EOF
 Usage: hyakvnc install [install options...]
- 
+	
 Description:
-  Install hyakvnc so the "hyakvnc" command can be run from anywhere.
+	Install hyakvnc so the "hyakvnc" command can be run from anywhere.
 
 Options:
-  -h, --help			Show this help message and exit
-  -i, --install-dir		Directory to install hyakvnc to (default: ~/.local/bin)
-  -s, --shell {bash|zsh}	Shell to install hyakvnc for (default: \$SHELL or bash)
+	-h, --help			Show this help message and exit
+	-i, --install-dir		Directory to install hyakvnc to (default: ~/.local/bin)
+	-s, --shell {bash|zsh}	Shell to install hyakvnc for (default: \$SHELL or bash)
 
 Examples:
-  # Install
-  hyakvnc install
-  # Install to ~/bin:
-  hyakvnc install -i ~/bin
+	# Install
+	hyakvnc install
+	# Install to ~/bin:
+	hyakvnc install -i ~/bin
 EOF
 }
 
+# cmd_install()
 function cmd_install {
 	local install_dir thisfile myshell shellrcpath
 	thisfile="${BASH_SOURCE[0]:-$0}"
@@ -876,6 +893,9 @@ function cmd_install {
 	[ "$myshell" == "zsh" ] && echo "Run 'rehash' to update your PATH"
 }
 
+# ## COMMAND: help
+
+# help_help()
 function cmd_help {
 	local action_to_help
 	local isinstalled
@@ -915,6 +935,9 @@ EOF
 	${action_to_help} "$@"
 }
 
+# Main
+
+# main()
 function main {
 	local action the_arg
 	for the_arg in "$@"; do
